"""empty message

Revision ID: 2cfdd21fee17
Revises: a64b68f4c4e5
Create Date: 2020-08-12 16:17:27.967313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cfdd21fee17'
down_revision = 'a64b68f4c4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_email', sa.String(length=120), nullable=False),
    sa.Column('recipient_email', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.Column('time_sent', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_email'], ['user.email'], ),
    sa.ForeignKeyConstraint(['sender_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('private_messages')
    # ### end Alembic commands ###
