"""empty message

Revision ID: f7572d649e3c
Revises: 45f214b25e96
Create Date: 2020-07-01 14:43:03.561177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7572d649e3c'
down_revision = '45f214b25e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friend_one', sa.Integer(), nullable=False),
    sa.Column('friend_two', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_one'], ['user.id'], ),
    sa.ForeignKeyConstraint(['friend_two'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
